# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.


##
# Site settings
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:            Nick McCrea
url:              http://www.nickmccrea.com   # the base hostname & protocol for your site, e.g. http://example.com
baseurl:          ""                          # the subpath of your site, e.g. /blog
timezone:         America/New York
email:            nick@nickmccrea.com
phone:            305.602.4300
description: >
  Computer Engineering and Software Development in Miami, FL, USA.
github_username:  nmccrea
disqus:
  shortname:      nick-mccrea-blog


##
# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock


##
# Jekyll Assets settings
assets:
  assets:
    - "*.jpg"


##
# Defaults
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post